version: '3.4'

services:
  httpbaselinetest_dev:
    container_name: httpbaselinetest_dev
    build:
      context: .
      target: dev
    volumes:
      - ${GOPATH:-~/go}:/go:cached
      - /private/var/folders:/var/folders:cached
      - ${PWD}:${PWD}
    working_dir: ${PWD}
